### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TH3GOD88** [swichers/xdk-assist#1]
I am having trouble getting the program you said is needed, as the Delphi only has a version 10. So I don't know if that is a problem or not.

**Comment by swichers** [comment]
You are correct that Delphi 2007 is unavailable for purchase these days. XDK Assist is 13 years old at this point. Its code was originally written using Delphi 2007 and its bundled Indy 10.1.1 controls. Anything newer than that may work, but is completely untested.

If you only want to run this program, you can download one of the binary releases and they should work. 

If you want to develop for it then you would need to make the effort to get it working on a modern Delphi (or Pascal) environment. I would be open to a pull request that had updates to make this compatible with modern Delphi, if you go that route.

Out of curiosity, what are you using XDK Assist for?

**Comment by TH3GOD88** [comment]
I was trying to use it to make a trainer for Magic the Gathering: Battle Grounds. I know not much of coding. but I follow directions pretty well, lol.

**Comment by swichers** [comment]
Ah, then you can try one of the two binary options here https://github.com/swichers/xdk-assist/releases/tag/1.0.0

It's likely to be an easier way to get up and running.

**Comment by TH3GOD88** [comment]
I tried that, but it complains of IndySystem100.bpl and IndyCore100.bpl are missing and I cannot find them in any of the releases on IndyProject.
